#!/bin/bash

if [ ! $# -eq 2 ]; then
        echo Invalid number of arguments!
        exit 1
fi

DIR="${1}"
STRING="${2}"

[ -d "${DIR}" ] || { echo "First argument must be a directory!"; exit 2; }

GLOBAL_VERSION=$(find ./kern/ -maxdepth 1 -mindepth 1 -type f | cut -d '/' -f3 | egrep "vmlinuz\-[0-9]+\.[0-9]+\.[0-9]+\-${STRING}" | cut -d'-' -f2 | sort -n | tail -n 1)

find ./kern/ -maxdepth 1 -mindepth 1 -type f | cut -d '/' -f3 | egrep "vmlinuz\-${GLOBAL_VERSION}\-${STRING}"
~                                                                              
~                                      
