#!/bin/bash

if [ ! $# -eq 2 ]; then 
	echo Invalid number of arguments!
	exit 1
fi

if [[ ! "${1}" =~ ^[0-9]+$ ]]; then
	echo "Not an integer"
	exit 3 
fi

if [[ ! "${2}" =~ ^[0-9]+$ ]]; then
	echo "Not an integer"
	exit 3 
fi
 
while read FILE; do
	LINE_NUMBER=$(cat "${FILE}" | wc -l )
	if [ "${1}" -gt "${LINE_NUMBER}" ]; then
		if [ ! -d ~/scripts/task3test/a ]; then 
			echo "Directory a doesn't exitst..."
			echo "Creating directory a..."
			mkdir ~/scripts/task3test/a
			mv "${FILE}" ~/scripts/task3test/a  
		else
			mv "${FILE}" ~/scripts/task3test/a 
		fi
	elif [ "${1}" -lt "${LINE_NUMBER}" -a "${2}" -gt "${LINE_NUMBER}" ]; then 
		if [ ! -d ~/scripts/task3test/b ]; then 
			echo "Directory b doesn't exitst..."
			echo "Creating directory b..."
			mkdir ~/scripts/task3test/b
			mv "${FILE}" ~/scripts/task3test/b 
		else
			mv "${FILE}" ~/scripts/task3test/b
		fi	
	else 
		if [ ! -d ~/scripts/task3test/c ]; then 
			echo "Directory c doesn't exitst..."
			echo "Creating directory c..."
			mkdir ~/scripts/task3test/c
			mv "${FILE}" ~/scripts/task3test/c 
		else
			mv "${FILE}" ~/scripts/task3test/c 
		fi

	fi
done < <(find . -maxdepth 1 -type f)
