#!/bin/bash

[ $# -eq 3 ] || { echo "Invalid number of arguments!"; exit 1; }

SRC="${1}"
DST="${2}"
ABC="${3}"

[ $(id -u) -eq 0 ] || { echo "Try again as a root user!"; exit 2; }
[ -r "${SRC}" ] || { echo "Directory "${SRC}" is not readable!"; exit 3; }
[ -r "${DST}" ] || { echo "Directory "${DST}" is not readable!"; exit 4; }


DIR_NAME=$(dirname "${0}")
while read LINE;do
	BASE_NAME=$(basename "${LINE}")
	dir_name=$(dirname "${LINE}")
	if [ ! -d "${DST}"/"${dir_name}" ]; then
		mkdir -p "${DST}"/"${dir_name}"
	fi
	cp "${LINE}" "${DST}"/"${dir_name}"/"${BASE_NAME}"

done< <(find ${SRC} -type f -name '*'"${ABC}"'*' 2>/dev/null)
