#!/bin/bash

if [ ! $# -eq 2 ]; then 
	echo Invalid number of arguments!
	exit 1
fi
FILE_NAME="${1}"
DIR_NAME="${2}"

[ -e "${FILE_NAME}" ] || { echo "File doesn't exits!"; exit 2; }
[ -d "${DIR_NAME}" ] || { echo "Directory doesn't exits!"; exit 3; }

[ ! $(ls -A "${DIR_NAME}") ]  || { echo "not empty dir!"; exit 3; }	
	NR=0
while read NAME; do	
	echo "${NAME};$((NR++))" >> "${DIR_NAME}"/dict.txt 
	egrep '^[A-Za-z]+ [A-Za-z]+((:)? | (\([A-Za-z]+ [A-Za-z]+\))?:) {0,}.*$' "${FILE_NAME}" | egrep "${NAME}" | cut -d ':' -f2 >> "${DIR_NAME}"/"${NR}".txt
done< <(egrep '^[A-Za-z]+ [A-Za-z]+((:)? | (\([A-Za-z]+ [A-Za-z]+\))?:) {0,}.*$' "${FILE_NAME}"| egrep -o '^[A-Za-z]+ [A-Za-z]+' | sort | uniq )
