#!/bin/bash

[ $(id -u) -eq 0 ] || exit 0 

while read USER HOME_DIR; do
	if [ ! -d "${HOME_DIR}" ] || sudo -u "${USER}" [ ! -w "${HOME_DIR}" ];then 
		echo "${USER}"
	fi
done  < <(cat /etc/passwd | awk -F : '{print $1,$6}' )
