#!/bin/bash

while read USER_NAME DIR; do
	if [ -r "${DIR}" ];then 
		echo "$USER_NAME"
		
		var=$(find "${DIR}" -type f 2>/dev/null -printf '%T@ %f\n' | sort -n -t ' ' -k1|tail -n 1 | cut -d ' ' -f2)
		echo "recently modified file in "${DIR}" is ${var}"
	else
		echo "Directory ${DIR} is not readable!"
	fi
done< <(cat /etc/passwd | awk -F ':' '{print $1,$6}')
