#!/bin/bash 

if [ $# -eq 0 ]; then
        echo "At least one argument is needed! "
        exit 1
fi

for FILE; do
        if  [ -d "${FILE}" ]; then
                NUMBER_OF_FILES=$(ls "${FILE}" | wc -l)
                find "${FILE}" -maxdepth 1 -mindepth 1 -type f -printf "%f %s \n" | awk '$2<'${NUMBER_OF_FILES}' {print $1}'
                shift 1
        elif [ -r "${FILE}" ];then
                echo ""${FILE} "- readable file" 
                shift 1
        fi
done
