#!/bin/bash

if [ ! $# -eq 1 ];then
	echo "Invalid number of parameters!" 
	exit 1 
fi	

USERNAME="${1}"

if [ ! $(ps -u "${USERNAME}") -eq 0 ];then
	echo "Invalid username! "
	exit 2
fi
CNT=0
while read PID;do #read -d $'\n' PID
	kill - 15 "${PID}"
	sleep 1 
	kill -9 "${PID}"
	CNT=$((CNT+1))	
done < <(ps -u "${USERNAME}" -o pid=)
echo "Total: ${CNT} killed processes "
